### ISSUE TITLE
Issue: When save fails, it shows fields from 1st tab, but remain last tab selected.

### ISSUE THREAD

**Issue by wemersonrv** [armincms/nova-tab#2]
Hi, when try to save a form with more than one tabs, and save faiils for any reason (validation or other stuffs), it shows the first tab content, but remains focus on tab that was active when try to save

I've recorded a screen showing the issue... note that when try to save, it was on 2nd tab and (**Documentos**) after save fails, it shows fields from 1st (**Geral**) but remains 2nd tab selected...

https://drive.google.com/file/d/1b0fEqSk54XNYMYk-T5hNEFqVdNkOg-kN/view?usp=sharing

**Comment by wemersonrv** [comment]
Hello, did was able to reproduce this issue ?

Did you need more information or tests ?

**Comment by zareismail** [comment]
Hi. Thanks for reporting.
You can use new macro method `withTab` for  each missed fields; this method added to `nova-tab` version 0.4.0
