### ISSUE TITLE
Question: How can i hide a tab item when creating a resource?

### ISSUE THREAD

**Issue by wemersonrv** [armincms/nova-tab#4]
Hi.

Nova Fields has several methods to show / hide fields in form/detail/index views... but the tab itens are not a field, but a part of a field.

I need to show some tabs only in edit form, and hide them from create form. So i've tried `hideWhenCreating` method, but of course, not works.

Is there a way to do that ?

**Comment by zareismail** [comment]
Hi.
At this time this feature is not available.

**Comment by wemersonrv** [comment]
> Hi.
> At this time this feature is not available.

Hi, this option is important because sometimes we need to show only a couple of fiels in creation and in details or edit form other fields... So i think that organizing them into tabs is good.

Exmple: In my `Cliente` resource, i have two tabs that i need to show on creation: **General** and **Documents** and after created nee to show a couple of related resources, each one in a spedific tab: `Contacts`, `Addresses`, `Owners`. See below:

![image](https://user-images.githubusercontent.com/2028673/68075177-0fda0400-fd83-11e9-84a7-6d391fb13226.png)


This is one of possible reasons to do this kind hiding tabs...

**Comment by zareismail** [comment]
> > Hi.
> > At this time this feature is not available.
> 
> Hi, this option is important because sometimes we need to show only a couple of fiels in creation and in details or edit form other fields... So i think that organizing them into tabs is good.
> 
> Exmple: In my `Cliente` resource, i have two tabs that i need to show on creation: **General** and **Documents** and after created nee to show a couple of related resources, each one in a spedific tab: `Contacts`, `Addresses`, `Owners`. See below:
> 
> ![image](https://user-images.githubusercontent.com/2028673/68075177-0fda0400-fd83-11e9-84a7-6d391fb13226.png)
> 
> This is one of possible reasons to do this kind hiding tabs...

Hi.
You are right;
But at this time; I don't have enough time to implement this feature.

**Comment by wemersonrv** [comment]
> > > Hi.
> > > At this time this feature is not available.
> > 
> > 
> > Hi, this option is important because sometimes we need to show only a couple of fiels in creation and in details or edit form other fields... So i think that organizing them into tabs is good.
> > Exmple: In my `Cliente` resource, i have two tabs that i need to show on creation: **General** and **Documents** and after created nee to show a couple of related resources, each one in a spedific tab: `Contacts`, `Addresses`, `Owners`. See below:
> > ![image](https://user-images.githubusercontent.com/2028673/68075177-0fda0400-fd83-11e9-84a7-6d391fb13226.png)
> > This is one of possible reasons to do this kind hiding tabs...
> 
> Hi.
> You are right;
> But at this time; I don't have enough time to implement this feature.

No problem. I'm just trying to contribute any way I can!

I was able to do it with a workaround using nova stuffs, by checking if the `$request` is a `\Laravel\Nova\Http\Requests\ResourceDetailRequest` instance... see:

```php
public function fields(Request $request)
{
    return [
        Tab::make('fist-tab', function($tab) use($request){
            $tab->group('general', [
                ID::make()->sortable()->hideFromIndex(),
                ...
            ])->label('Geral');

            $tab->group('docs', [
                ...
            ])->label('Documentos');

            if ($request instanceof \Laravel\Nova\Http\Requests\ResourceDetailRequest) {
                $tab->group('contacts', [
                    ...

                $tab->group('addresses', [
                    ...
            }
        }),
    ];
}
```
