### ISSUE TITLE
Issue: $tabs are repeating fields from another tabs in Details View

### ISSUE THREAD

**Issue by wemersonrv** [armincms/nova-tab#5]
Hello, greetings from Brazil.

The tabs are working fine in `form` view. as you can see here:

**Form View** (Fields are fine, each in their own tab)
![image](https://user-images.githubusercontent.com/2028673/68075430-9b08c900-fd86-11e9-9751-00d10035f62c.png)

But, in `details view`, each tab tabs shows fields from all tabs... see:

**Details View** (fields from another tabs repeats on each tab)
![image](https://user-images.githubusercontent.com/2028673/68075464-ec18bd00-fd86-11e9-84a2-48e1ca3c47ce.png)

**Comment by wemersonrv** [comment]
Hello, trying to make contribution here... after an analisys on your code, i realized that some fields misses the `tab-hidden` style class property and because that they repeats on each tab group. 

But i don't understand very well the logic behind to change it properly and make a PR...

**Comment by zareismail** [comment]
Hi. Thanks for reporting.
You can use new macro method `withTab` for  each missed fields; this method added to `nova-tab` version 0.4.0

**Comment by wemersonrv** [comment]
> Hi. Thanks for reporting.
> You can use new macro method `withTab` for each missed fields; this method added to `nova-tab` version 0.4.0

Hi.

I don't understand why using `withTab` because the fields are in a specific `$tab->gorup('any-group'...`. Adding the field to this group with `withTab('any-group')` isn't the same thing?

**Comment by zareismail** [comment]
> > Hi. Thanks for reporting.
> > You can use new macro method `withTab` for each missed fields; this method added to `nova-tab` version 0.4.0
> 
> Hi.
> 
> I don't understand why using `withTab` because the fields are in a specific `$tab->gorup('any-group'...`. Adding the field to this group with `withTab('any-group')` isn't the same thing?

Because; the package can't find fields under the `conditional-container` fields.
