### ISSUE TITLE
Resource tool on all tabs

### ISSUE THREAD

**Issue by martinmildner** [armincms/nova-tab#7]
Hi there!

Thanks for the package, works like charm.

I've found one problem regarding  resource tools. They are shown on each tab, although the tool has been added within one $tab->group.

Any ideas?
Thanks for your help!
martin 

<img width="1754" alt="Bildschirmfoto 2019-12-04 um 16 31 25" src="https://user-images.githubusercontent.com/789541/70156264-f266c580-16b3-11ea-9ac5-44faa4c88eb9.png">

**Comment by zareismail** [comment]
hi. thank's for reporting.
you can resolve this situation by `->withTab('tab-name', 'group-name')` method.see [here](https://github.com/armincms/nova-tab#missed-tabs)

**Comment by martinmildner** [comment]
`->withTab('tab-name', 'group-name')` works fine with "normal" fields, but had no luck with a resource tool. did it work on your side? the resource tool is still below each tab.
<img width="555" alt="Bildschirmfoto 2019-12-05 um 08 14 25" src="https://user-images.githubusercontent.com/789541/70212357-6ac29a80-1737-11ea-9b33-d32f4f8a1572.png">
<img width="533" alt="Bildschirmfoto 2019-12-05 um 08 15 17" src="https://user-images.githubusercontent.com/789541/70212364-6e562180-1737-11ea-81df-07cf1417ddca.png">
<img width="546" alt="Bildschirmfoto 2019-12-05 um 08 16 26" src="https://user-images.githubusercontent.com/789541/70212439-92b1fe00-1737-11ea-8511-f02dadfcaa3d.png">

**Comment by zareismail** [comment]
> `->withTab('tab-name', 'group-name')` works fine with "normal" fields, but had no luck with a resource tool. did it work on your side? the resource tool is still below each tab.
> <img alt="Bildschirmfoto 2019-12-05 um 08 14 25" width="555" src="https://user-images.githubusercontent.com/789541/70212357-6ac29a80-1737-11ea-9b33-d32f4f8a1572.png">
> <img alt="Bildschirmfoto 2019-12-05 um 08 15 17" width="533" src="https://user-images.githubusercontent.com/789541/70212364-6e562180-1737-11ea-81df-07cf1417ddca.png">
> <img alt="Bildschirmfoto 2019-12-05 um 08 16 26" width="546" src="https://user-images.githubusercontent.com/789541/70212439-92b1fe00-1737-11ea-8511-f02dadfcaa3d.png">

I'm sorry, but this package does not support `ResourceTool`
